[project]
authors = [
    {name = "Dmitry Gritsenko", email = "runevery@evtn.me"},
]
license = {text = "MIT"}
requires-python = "<4.0,>=3.8"
dependencies = [
    "typing-extensions<5.0.0,>=4.12.1",
]
name = "runevery"
version = "0.6.1"
description = ""
readme = "README.md"
keywords = []

[project.urls]
homepage = "https://github.com/evtn/runevery"
repository = "https://github.com/evtn/runevery"

[dependency-groups]
dev = [
    "pytest<8.0.0,>=7.4.0",
    "coverage<8.0.0,>=7.2.7",
    "pyrefly>=0.51.1",
    "ruff>=0.15.0",
]
