name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - lord
    paths:
      - "**.py"
      - "**.yml"
  pull_request:
    paths:
      - "**.py"
      - "**.yml"
jobs:
  check:
    runs-on: ubuntu-latest
    name: Check Types & Linter
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.4"

      - name: Run typecheck
        run: uv run pyrefly check

      - name: Run linter
        run: uv run ruff check
